### ISSUE TITLE
Add border-radius tokens

### ISSUE THREAD

**Issue by Teddarific** [magicpatterns/mirrorful#12]
Add a new section for `border radii`

Should allow for variations, such as:

- `base`
- `sm`
- `md`
- `lg`

**Comment by prichter** [comment]
@Teddarific - can you please elaborate a little more, and assign this to me?  A user story might help me with context...  Would this potentially, for example, be a display block under the color shades showing the radius for different variations, and a separate edit modal to allow adjusting these values?

**Comment by prichter** [comment]
<img width="1056" alt="Screenshot 2023-03-02 200543" src="https://user-images.githubusercontent.com/1085675/222385263-3375433f-c956-4645-9930-de5dbd417fdc.png">
Maybe like this (pretending the radii are different sizes)?

**Comment by prichter** [comment]
<img width="751" alt="Screenshot 2023-03-02 202013" src="https://user-images.githubusercontent.com/1085675/222388309-2dd141c9-ce7c-45aa-9376-9344bb06d330.png">

**Comment by alexdanilowicz** [comment]
@prichter , you're on the right track. We need to think about it more ourselves, so appreciate you creating a mockup. Will think about it some more. 

I think it would be a separate section, like how we just added "Typography". And the section would be called Spacing.

Need to think some more. cc @Teddarific

**Comment by Teddarific** [comment]
Hey @prichter! Love the mock-ups — going to put this one on hold for now. We want to really nail the experience down for colors, so that once we expand, we can build ontop of a great base.

If you want to put up an initial PR with the functionality, happy to merge it in without the UI, that would be a great help!

**Comment by prichter** [comment]
@Teddarific this was just a wireframe - if I get some time I might knock up a few bits of the functionality.
