### ISSUE TITLE
Create generic modal component

### ISSUE THREAD

**Issue by alexdanilowicz** [magicpatterns/mirrorful#156]
Right now, the EditFont Modal and EditColor Modal are different. We should have have generic modal component. 
 
 **Some thoughts:**
 - "making this component right now is probably a case of making an abstraction before we know all the use cases, token data model, etc. Though I don't object to making a super generic token modal right now, at least something that could help standardize the layout (i.e., header, footer buttons, etc.)"
 - "if there was a standard(ish) modal, there's less to think about when adding new features - Need new tokens? here's a modal you can bang it into, no need to worry about going back and fixing to be consistent later...  I get your point about lock-in, but most tokens have edit name, value, delete, save options"

**Comment by alexdanilowicz** [comment]
@zachsnoek would you say this issue is the same as

> - Modal titles, button text, and input labels should have consistent font sizes, wording, and casing

Is this what you meant? Coming from this Slack [thread](https://mirrorful.slack.com/archives/C04QRA1GA4C/p1678663135944999).

**Comment by zachsnoek** [comment]
> @zachsnoek would you say this issue is the same as
> 
> > * Modal titles, button text, and input labels should have consistent font sizes, wording, and casing
> 
> Is this what you meant? Coming from this Slack [thread](https://mirrorful.slack.com/archives/C04QRA1GA4C/p1678663135944999).

I think it's within the same scope––though I think we could make two separate issues out of that Slack thread:

1. Create generic modal component (this issue) with consistent titles, button text, labels, etc.
2. Standardize headings, button text, etc. everywhere else in the app.

For the second, examples of this would be: "Color Palette" heading is a different size than "Typography" heading, and the font size variant button says "Add New Font Size" while the add color button says "Add a new color."

**Comment by alexdanilowicz** [comment]
Understood, I'm actually going to hold off on creating:

> Standardize headings, button text, etc. everywhere else in the app. ... examples of this would be: "Color Palette" heading is a different size than "Typography" heading, and the font size variant button says "Add New Font Size" while the add color button says "Add a new color."

because I _know_ things are going to change very rapidly. Teddy will be making some Figmas soon, but we hear you and definitely want to improve the UX and have a consistent experience. that is our mission, after all! We actually are going to start using Mirrorful in Mirrorful which will be great!

**Comment by alexdanilowicz** [comment]
@zachsnoek by chance are you interested in this issue at all?
