### ISSUE TITLE
Color Palette: Allow user to undo and reset changes to HSL values while modifying color themes

### ISSUE THREAD

**Issue by Pranav2612000** [magicpatterns/mirrorful#406]
On the [colors](https://app.mirrorful.com/colors) page, the user can click on the edit color icon to open up HSL sliders to change the color. We also need to add functionality to allow the user to undo and reset the changes to the sliders.

<img width="337" alt="image" src="https://github.com/Mirrorful/mirrorful/assets/20909078/fb43f961-a022-430b-b23d-8fcb55f9c851">

Before writing the code, it would be good to discuss how these functionalities would work, where the buttons would be located and how would they look.

**Comment by Pranav2612000** [comment]
Makes sense @Bismay5467 . I'm not sure what a good UX could be. Let's see what @alexdanilowicz has to say.

Also should the `undo` & `redo` be slider specific or for a color value ( combination of HSL )

One user flow I can think of is – As a user, I play around with the HSL values to see if I'm able to find a different color I like, but I am not able to, so I'll now like to revert back my changes ( all 3 sliders ) to the original color value.

But at the same time, since we are using sliders, it's also very common to mistakenly move the slider to an unexpected place and then wanting to move it back to its previous position.

**Comment by alexdanilowicz** [comment]
@Bismay5467 @Pranav2612000 let me think about this and maybe I can provide a Figma mock. I think we would want to mimic tailwind shades: https://www.tailwindshades.com/#color=156%2C22.93577981651376%2C21.372549019607845&step-up=8&step-down=11&hue-shift=0&name=plantation&base-stop=8&v=1&overrides=e30%3D
