### ISSUE TITLE
Complementary palette's opacity should match primary's opacity

### ISSUE THREAD

**Issue by alexdanilowicz** [magicpatterns/mirrorful#413]
For example, if the primary is rgb(A,B,C, 0.25)... then the palette should be generated as  rgb(X,Y,Z, 0.25).

**Comment by noobCode-69** [comment]
Can you elaborate the issue, like how to reproduce this issue!

**Comment by alexdanilowicz** [comment]
Yes, steps to repro:

1. start with onboarding
2. make primary rgba, and change opacity to less than 100%
3. go through onboarding
4. expected behavior: the rest of pallete (the other colors) also have 0.25 opacity, not 100. 

https://github.com/Mirrorful/mirrorful/assets/29822597/c9d40819-327f-463e-92dc-950904c1fd43

**Comment by noobCode-69** [comment]
I could help with that!

**Comment by noobCode-69** [comment]
Little doubt here.
* How to start onboarding process , it happened when i first started the mirrorful , but not every time.
And yeah please assign it to me! I think i can do it.
