### ISSUE TITLE
HSL issue regarding lightness

### ISSUE THREAD

**Issue by victorjimoh** [magicpatterns/mirrorful#462]
I noticed a bug when trying to change the lightness of a colour. If you increase the lightness and reduce it. The other shades from 50-400 stay at #FFF and from 600 to 900, they are just shades of white. I attached a loom link to show the problem.

https://www.loom.com/share/e3bab1b9de3a4677b0e38f88a793a724

**Comment by larrybrazz** [comment]
Hi @alexdanilowicz I am a Frontend developer and this is my first time trying to contribute to an Open Source Project so  I will appreciate if you can explain to me how to help fix this bug .
