### ISSUE TITLE
Enter on color picker should save the value even when still in focus 

### ISSUE THREAD

**Issue by alexdanilowicz** [magicpatterns/mirrorful#472]
**Steps to repro:**
1. enter a color
2. while still focused on the input, hit enter
3. your color will not be saved
Expected behavior: enter saves your value. 

https://github.com/Mirrorful/mirrorful/assets/29822597/72fa52d1-2213-4b8b-b0c9-5052d63fda19

**Comment by Pranav2612000** [comment]
I'll like to work on this.

**Comment by noobCode-69** [comment]
Since it's been two days , I should help!!

**Comment by noobCode-69** [comment]
If you look at this code ColorPicker.tsx
```js
onChange={(e) => {
    setHexInputValue(e.target.value)
}}
onBlur={() => {
    /* Since the user may not have entered a valid hexcolor string, we parse it to convert it to a valid hexcolor string */
    const parsedHexString = parseHexString(
        hexInputValue,
        tinycolor(colorPickerColor).toHexString()
     )
     setHexInputValue(parsedHexString)
     onChange(parsedHexString)
}}
```
**The behaviour we are expecting** 
- User write the hex value (onChange get triggered updating the local state)
- he will click to the Submit button (onBlur get triggered converting the hexInputValue to valid one and then updating the primaryColor from the index.ts)

**Error**
- When the user directly press "Enter" , the onBlur never get a chance to get triggered

**Comment by noobCode-69** [comment]
Hey @alexdanilowicz please let me know if this works!!

**Comment by alexdanilowicz** [comment]
Sorry I missed this @Pranav2612000 . @noobCode-69 looks good! will merge today.

apologies as this slipped by my notifications
