### ISSUE TITLE
Allow ability to change palette colors on onboarding screen 

### ISSUE THREAD

**Issue by alexdanilowicz** [magicpatterns/mirrorful#474]
<img width="1062" alt="Screen Shot 2023-05-24 at 2 41 44 PM" src="https://github.com/Mirrorful/mirrorful/assets/29822597/83001940-2cab-456e-a63e-4307f6c13a7e">

**Comment by noobCode-69** [comment]
I am working on this!!

**Comment by betty-alagwu** [comment]
Hello @alexdanilowicz I'll like to work on this
