### ISSUE TITLE
Mobile Responsiveness: Sidebar to be closed be default on mobile when page loads

### ISSUE THREAD

**Issue by Pranav2612000** [magicpatterns/mirrorful#483]
Right now, when I visit the mirrorful home page, the sidebar is open by default. In line with how the hamburger icons works across most sites, the sidebar should be closed by default and open up when a user clicks on the hamburger icon

**Comment by Pranav2612000** [comment]
Thoughts? @alexdanilowicz

**Comment by alexdanilowicz** [comment]
I think it should be closed by default _on mobile_ .

This is what you mean, yes? @Pranav2612000

**Comment by betty-alagwu** [comment]
@Pranav2612000 @alexdanilowicz i'd love to work on this

**Comment by Pranav2612000** [comment]
Sure @betty-alagwu ! Go ahead.

**Comment by lazyfuhrer** [comment]
Is it still open? I'd like to give a shot @Pranav2612000
